### ISSUE TITLE
Team & TeamMemberships support

### ISSUE THREAD

**Issue by ObjectIsAdvantag** [NGMarmaduke/cisco_spark-ruby#2]
Are you considering supporting the new Cisco Spark API resources ?

May check this other community contribution that integrates the new API, with MIT License support.
https://github.com/Cloverhound/ciscospark-ruby

**Comment by NGMarmaduke** [comment]
Hi @ObjectIsAdvantag, thanks for the heads up - absolutely I'll add Teams; I'll let you know when the support is added.

**Comment by ObjectIsAdvantag** [comment]
excellent, FYI your library is referenced in https://github.com/ObjectIsAdvantag/awesome-ciscospark, the cisco spark ruby community will be delighted to see this update coming ! Keep the good work ...

**Comment by NGMarmaduke** [comment]
Closed with the work from @dalpo 💯
